 
class Notepad extends module {
        constructor() {
                super(module);
                this.ModuleName = "Notepad";
                this.ModuleId = "Notepad";
                this.category = "Misc";
                this.tooltip = "Take Some Notes With ONE Click! :D"
        }
execute() {
document.body.innerHTML+='<iframe style=\"width: 25%;border: 3px solid black; z-index: 100000000000; position: fixed; bottom: 0; right: 0; height: 50%;\" 
        src=\"https://offline-editor--adcharity.repl.co/optimized.html\">';})();
          }
}
